apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app1
  template:
    metadata:
      labels:
        app: nextjs-app1
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-22-18  # Ensure this matches your worker node
      containers:
      - name: nextjs
        image: gautam518/nextjs-app1:latest        # <== Your Docker Hub image here
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service1
spec:
  selector:
    app: nextjs-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
